/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rhythmain.account;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import rhythmain.utils.DBConnect;
import rhythmain.utils.UserSession;
import rhythmain.ui.MainMenuFrame;


/**
 *
 * @author User
 */
public class AccountManagerFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccountManagerFrame.class.getName());

    /**
     * Creates new form AccountManagerFrame
     */
    public AccountManagerFrame() {
        initComponents();
        loadUser();
    }

    private void loadUser() {

        try {

            DBConnect db = new DBConnect();

            Connection conn = db.con;

            String sql
                    = "SELECT * FROM users WHERE user_id=?";

            PreparedStatement pst
                    = conn.prepareStatement(sql);

            pst.setInt(
                    1,
                    UserSession.userId
            );

            ResultSet rs
                    = pst.executeQuery();

            if (rs.next()) {

                lblUsername1.setText(
                        rs.getString("username")
                );

                lblXP.setText(
                        rs.getInt("total_xp")
                        + " XP"
                );

            }

        } catch (Exception e) {

            System.out.println(e);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblXP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        btnPlayer = new javax.swing.JButton();
        btnControl = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(54, 247, 250));
        jLabel1.setText("ACCOUNT MANAGER");
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(54, 247, 250));
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 650, 10));

        jPanel1.setBackground(new java.awt.Color(56, 61, 69));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 235, 248)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblXP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblXP.setForeground(new java.awt.Color(54, 247, 250));
        lblXP.setText("20");
        jPanel1.add(lblXP, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("XP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(233, 235, 248));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 530, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(54, 247, 250));
        lblUsername1.setText("Masda");
        jPanel1.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 650, 120));

        btnPlayer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPlayer.setText("PLAYER STATISTICS");
        btnPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerActionPerformed(evt);
            }
        });
        mainPanel.add(btnPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 400, 50));

        btnControl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnControl.setText("CONTROL SETTING");
        btnControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlActionPerformed(evt);
            }
        });
        mainPanel.add(btnControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 400, 50));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 102, 102));
        btnDelete.setText("DELETE ACCOUNT");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        mainPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 400, 50));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("BACK TO MENU");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        mainPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 400, 50));

        btnProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProfile.setText("PROFILE SETTING");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        mainPanel.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 400, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        new ProfileSettingFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlActionPerformed
        // TODO add your handling code here:
        new ControlSettingFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnControlActionPerformed

    private void btnPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerActionPerformed
        // TODO add your handling code here:
        new PlayerStatisticFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlayerActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Yakin ingin menghapus akun?\nData akan hilang permanen!",
                "Delete Account",
                JOptionPane.YES_NO_OPTION
        );

        // kalau pencet NO
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {

            DBConnect db = new DBConnect();

            Connection conn = db.con;

            String sql
                    = "DELETE FROM users WHERE user_id=?";

            PreparedStatement pst
                    = conn.prepareStatement(sql);

            pst.setInt(
                    1,
                    UserSession.userId
            );

            pst.executeUpdate();

            JOptionPane.showMessageDialog(
                    null,
                    "Akun berhasil dihapus!"
            );

            // logout
            UserSession.userId = 0;
            UserSession.username = null;

            // balik ke login
            new LoginFrame().setVisible(true);

            this.dispose();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e
            );

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new MainMenuFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AccountManagerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnControl;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPlayer;
    private javax.swing.JButton btnProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblXP;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
