/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rhythmain.account;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

import rhythmain.utils.DBConnect;
import rhythmain.utils.UserSession;

/**
 *
 * @author User
 */
public class ControlSettingFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ControlSettingFrame.class.getName());

    /**
     * Creates new form ControlSettingFrame
     */
    public ControlSettingFrame() {
        initComponents();
        loadControl();
    }

    private void loadControl() {

        try {

            DBConnect db = new DBConnect();

            Connection conn = db.con;

            String sql
                    = "SELECT * FROM users WHERE user_id=?";

            PreparedStatement pst
                    = conn.prepareStatement(sql);

            pst.setInt(
                    1,
                    UserSession.userId
            );

            ResultSet rs
                    = pst.executeQuery();

            if (rs.next()) {

                String key
                        = rs.getString("key_bindings");

                txtUp.setText(
                        String.valueOf(key.charAt(0))
                );

                txtDown.setText(
                        String.valueOf(key.charAt(1))
                );

                txtLeft.setText(
                        String.valueOf(key.charAt(2))
                );

                txtRight.setText(
                        String.valueOf(key.charAt(3))
                );

                sliderSpeed.setValue(
                        (int) (rs.getDouble("scroll_speed")
                        * 10)
                );

            }

        } catch (Exception e) {

            System.out.println(e);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRight = new javax.swing.JTextField();
        txtUp = new javax.swing.JTextField();
        txtDown = new javax.swing.JTextField();
        txtLeft = new javax.swing.JTextField();
        sliderSpeed = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(54, 247, 250));
        jLabel1.setText("CONTROL SETTING");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(54, 247, 250));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 650, 10));

        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Scroll Speed");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Key Up");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Key Down");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Key Left");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        txtRight.setBackground(new java.awt.Color(58, 64, 75));
        txtRight.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtRight.setForeground(new java.awt.Color(54, 247, 250));
        txtRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRightActionPerformed(evt);
            }
        });
        jPanel2.add(txtRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 240, 40));

        txtUp.setBackground(new java.awt.Color(58, 64, 75));
        txtUp.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUp.setForeground(new java.awt.Color(54, 247, 250));
        txtUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpActionPerformed(evt);
            }
        });
        jPanel2.add(txtUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 240, 40));

        txtDown.setBackground(new java.awt.Color(58, 64, 75));
        txtDown.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDown.setForeground(new java.awt.Color(54, 247, 250));
        txtDown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDownActionPerformed(evt);
            }
        });
        jPanel2.add(txtDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 240, 40));

        txtLeft.setBackground(new java.awt.Color(58, 64, 75));
        txtLeft.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtLeft.setForeground(new java.awt.Color(54, 247, 250));
        txtLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeftActionPerformed(evt);
            }
        });
        jPanel2.add(txtLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 240, 40));

        sliderSpeed.setBackground(new java.awt.Color(54, 247, 250));
        jPanel2.add(sliderSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Key Right");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSave.setFocusPainted(false);
        btnSave.setName(""); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new AccountManagerFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void txtRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRightActionPerformed

    private void txtUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpActionPerformed

    private void txtDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDownActionPerformed

    private void txtLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeftActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here
        try {

            DBConnect db = new DBConnect();

            Connection conn = db.con;

            String keyBindings
                    = txtUp.getText()
                    + txtDown.getText()
                    + txtLeft.getText()
                    + txtRight.getText();

            double speed
                    = sliderSpeed.getValue() / 10.0;

            String sql
                    = "UPDATE users SET "
                    + "key_bindings=?, "
                    + "scroll_speed=? "
                    + "WHERE user_id=?";

            PreparedStatement pst
                    = conn.prepareStatement(sql);

            pst.setString(
                    1,
                    keyBindings
            );

            pst.setDouble(
                    2,
                    speed
            );

            pst.setInt(
                    3,
                    UserSession.userId
            );

            pst.executeUpdate();

            JOptionPane.showMessageDialog(
                    null,
                    "Control berhasil disimpan!"
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e
            );

        }

    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ControlSettingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider sliderSpeed;
    private javax.swing.JTextField txtDown;
    private javax.swing.JTextField txtLeft;
    private javax.swing.JTextField txtRight;
    private javax.swing.JTextField txtUp;
    // End of variables declaration//GEN-END:variables
}
