/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rhythmain.ui;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import rhythmain.account.AccountManagerFrame;
import rhythmain.account.ControlSettingFrame;
import rhythmain.account.LoginFrame;
import rhythmain.audio.AudioPlayer;
import rhythmain.utils.BeatmapReader;
import rhythmain.utils.Note;
import rhythmain.utils.UserSession;

/**
 *
 * @author gante
 */
public class MainMenuFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuFrame.class.getName());
    
    // buat manajemen navigasi (card layout)
    private CardLayout cardLayout;
    private JPanel mainContainer;
    private AudioPlayer bgmPlayer;
    private String panelName;
    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
        
        setTitle("RhythMain - Rhyth Game Dekstop");
        setLocationRelativeTo(null);
        setResizable(false);
        
        bgmPlayer = new AudioPlayer();
        cardLayout = new CardLayout();
        mainContainer = new JPanel(cardLayout);
        
        mainContainer.add(jPanel1, "MainMenuPanel");
        
        setContentPane(mainContainer);
        cardLayout.show(mainContainer, "MainMenuPanel");
        
        jLabel2.setText("Hallo " + UserSession.username);
        
        updateLogoutButtonVisibility();
        
        this.setIconImage(new ImageIcon("./assets/icon.png").getImage());
    }
    
    private void updateLogoutButtonVisibility(){
        if (UserSession.username != null && !UserSession.username.equalsIgnoreCase("Guest")) {
            logoutButton.setVisible(true);
        } else {
            logoutButton.setVisible(false); 
        }
    }
    
    public void switchPanel(String panelName){
        cardLayout.show(mainContainer, panelName);
    }
    
    public AudioPlayer getBgmPlayer() {
        return bgmPlayer;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        accountButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("RhythMain - Rhythm Game Desktop");
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        judul.setFont(new java.awt.Font("Bernard MT Condensed", 0, 48)); // NOI18N
        judul.setForeground(new java.awt.Color(51, 255, 204));
        judul.setText("RhythMain");
        judul.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Halo, Guest!");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        playButton.setBackground(new java.awt.Color(242, 242, 242));
        playButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        playButton.setText("PLAY");
        playButton.addActionListener(this::playButtonActionPerformed);

        accountButton.setBackground(new java.awt.Color(242, 242, 242));
        accountButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        accountButton.setText("ACCOUNT");
        accountButton.addActionListener(this::accountButtonActionPerformed);

        settingsButton.setBackground(new java.awt.Color(242, 242, 242));
        settingsButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        settingsButton.setText("SETTINGS");
        settingsButton.addActionListener(this::settingsButtonActionPerformed);

        logoutButton.setBackground(new java.awt.Color(242, 242, 242));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        exitButton.setBackground(new java.awt.Color(242, 242, 242));
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.addActionListener(this::exitButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(playButton)
                .addGap(18, 18, 18)
                .addComponent(accountButton)
                .addGap(18, 18, 18)
                .addComponent(settingsButton)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addGap(18, 18, 18)
                .addComponent(exitButton)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
        SongSelectionFrame frame = new SongSelectionFrame();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_playButtonActionPerformed

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        // TODO add your handling code here:
        AccountManagerFrame frame = new AccountManagerFrame();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_accountButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
        ControlSettingFrame frame = new ControlSettingFrame();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        konfirmasiKeluar();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin logout?", "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (pilihan == JOptionPane.YES_NO_OPTION){
            LoginFrame frame = new LoginFrame();
            frame.setVisible(true);
            this.setVisible(false);
            
            JOptionPane.showMessageDialog(this, "Anda berhasil logout", "info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        konfirmasiKeluar();
    }//GEN-LAST:event_formWindowClosing

    private void konfirmasiKeluar(){
        int pilihan = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin keluar dari game RhythMain?", 
                "Konfirmasi Keluar", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);
        
        if (pilihan == JOptionPane.YES_OPTION) {
            if (bgmPlayer != null) {
                bgmPlayer.stop();
            }
            System.exit(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> new MainMenuFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton playButton;
    private javax.swing.JButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
