/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rhythmain.ui;
import java.sql.ResultSet;   // untuk mengambil hasil query
import java.sql.Statement;   // untuk membuat query untuk operasi crud
import javax.swing.JOptionPane;
import rhythmain.utils.DBConnect;

/**
 *
 * @author LENOVO
 */
public class SongSelectionPanel extends javax.swing.JFrame {
    DBConnect db;
    private int[] songIds;
    private int selectedSongId = -1;
    private int selectedBeatmapId = -1;
    private javax.swing.DefaultListModel<String> songListModel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SongSelectionPanel.class.getName());

    /**
     * Creates new form SongSelectionPanel
     */
    public SongSelectionPanel() {
        initComponents();
        db = new DBConnect();

        // Setup JList model
        songListModel = new javax.swing.DefaultListModel<>();
        songList.setModel(songListModel);

        // Setup leaderboard table
        leaderboardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"#", "Player", "Score", "Grade"}
        ) {
            public boolean isCellEditable(int r, int c) { return false; }
        });

        // Load semua lagu pertama kali
        loadSongs("");
    }
    
    private MainMenuFrame mainFrame;
    
    public SongSelectionPanel(MainMenuFrame mainFrame){
        this.mainFrame = mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaderboardTable = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        songList = new javax.swing.JList<>();
        btnEasy = new javax.swing.JButton();
        btnNormal = new javax.swing.JButton();
        btnHard = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(32, 32, 32));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("PILIH LAGU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(java.awt.Color.cyan);
        jLabel2.setText("Score Board");

        leaderboardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Player", "Score", "Grade"
            }
        ));
        jScrollPane1.setViewportView(leaderboardTable);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnCari.setText("cari lagu");
        btnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCariMouseClicked(evt);
            }
        });

        songList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        songList.addListSelectionListener(this::songListValueChanged);
        jScrollPane2.setViewportView(songList);

        btnEasy.setBackground(new java.awt.Color(153, 255, 0));
        btnEasy.setText("Easy");
        btnEasy.setEnabled(false);
        btnEasy.addActionListener(this::btnEasyActionPerformed);

        btnNormal.setBackground(new java.awt.Color(255, 255, 0));
        btnNormal.setText("Normal");
        btnNormal.setEnabled(false);
        btnNormal.addActionListener(this::btnNormalActionPerformed);

        btnHard.setBackground(new java.awt.Color(255, 102, 0));
        btnHard.setText("Hard");
        btnHard.setEnabled(false);
        btnHard.addActionListener(this::btnHardActionPerformed);

        btnPlay.setBackground(new java.awt.Color(0, 153, 204));
        btnPlay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("PLAY !");
        btnPlay.setEnabled(false);
        btnPlay.addActionListener(this::btnPlayActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCari)))
                                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEasy, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(btnNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEasy)
                                .addGap(18, 18, 18)
                                .addComponent(btnNormal)
                                .addGap(18, 18, 18)
                                .addComponent(btnHard)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseClicked
        // TODO add your handling code here:
        String keyword = txtSearch.getText().trim();
        if (keyword.equals("Cari lagu...") || keyword.isEmpty()) {
            loadSongs("");
        } else {
            loadSongs(keyword);
        }
    }//GEN-LAST:event_btnCariMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String keyword = txtSearch.getText().trim();
        if (!keyword.equals("Cari lagu...")) {
            loadSongs(keyword);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void songListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_songListValueChanged
        // TODO add your handling code here:
        int index = songList.getSelectedIndex();
        if (index >= 0 && songIds != null) {
            selectedSongId = songIds[index];
            // Aktifkan tombol difficulty
            btnEasy.setEnabled(true);
            btnNormal.setEnabled(true);
            btnHard.setEnabled(true);
            btnPlay.setEnabled(false);
            selectedBeatmapId = -1;
        }
    }//GEN-LAST:event_songListValueChanged

    private void btnEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEasyActionPerformed
        // TODO add your handling code here:
        selectDifficulty("Easy");
    }//GEN-LAST:event_btnEasyActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        // TODO add your handling code here:
        selectDifficulty("Normal");
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHardActionPerformed
        // TODO add your handling code here:
        selectDifficulty("Hard");
    }//GEN-LAST:event_btnHardActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        if (selectedBeatmapId == -1) {
            JOptionPane.showMessageDialog(this, "Pilih difficulty dulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Nanti disambungkan ke GameplayFrame oleh A3
            JOptionPane.showMessageDialog(this, "Memulai game dengan beatmap ID: " + selectedBeatmapId, "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SongSelectionPanel().setVisible(true));
    }

    private void loadSongs(String keyword) {
    songListModel.clear();
    selectedSongId = -1;
    selectedBeatmapId = -1;
    btnEasy.setEnabled(false);
    btnNormal.setEnabled(false);
    btnHard.setEnabled(false);
    btnPlay.setEnabled(false);

    try {
        String query;
        if (keyword.isEmpty()) {
            query = "SELECT song_id, title, artist FROM songs ORDER BY song_id";
        } else {
            query = "SELECT song_id, title, artist FROM songs " +
                    "WHERE title LIKE '%" + keyword + "%' " +
                    "OR artist LIKE '%" + keyword + "%' " +
                    "ORDER BY song_id";
        }

        java.sql.Statement st = db.con.createStatement();
        java.sql.ResultSet rs = st.executeQuery(query);

        java.util.List<Integer> idList = new java.util.ArrayList<>();
        while (rs.next()) {
            idList.add(rs.getInt("song_id"));
            songListModel.addElement(rs.getString("title") + " — " + rs.getString("artist"));
        }

        songIds = idList.stream().mapToInt(Integer::intValue).toArray();

        if (songListModel.isEmpty()) {
            songListModel.addElement("Tidak ada lagu ditemukan.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load lagu: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private void selectDifficulty(String diffName) {
    if (selectedSongId == -1) {
        JOptionPane.showMessageDialog(this, "Pilih lagu dulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        String query = "SELECT beatmap_id FROM beatmaps WHERE song_id = " + selectedSongId +
                       " AND difficulty_name = '" + diffName + "'";
        java.sql.Statement st = db.con.createStatement();
        java.sql.ResultSet rs = st.executeQuery(query);

        if (rs.next()) {
            selectedBeatmapId = rs.getInt("beatmap_id");
//            lblSelected.setText(lblSelected.getText().split("\\|")[0].trim() + " | Difficulty: " + diffName);
            btnPlay.setEnabled(true);
            loadLeaderboard(selectedBeatmapId);
        } else {
            JOptionPane.showMessageDialog(this, "Difficulty " + diffName + " belum tersedia.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private void loadLeaderboard(int beatmapId) {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) leaderboardTable.getModel();
    model.setRowCount(0);

    try {
        String query =
            "SELECT u.username, s.score, s.grade " +
            "FROM scores s " +
            "JOIN users u ON s.user_id = u.user_id " +
            "WHERE s.beatmap_id = " + beatmapId + " " +
            "ORDER BY s.score DESC " +
            "LIMIT 10";

        java.sql.Statement st = db.con.createStatement();
        java.sql.ResultSet rs = st.executeQuery(query);

        int rank = 1;
        while (rs.next()) {
            model.addRow(new Object[]{
                rank++,
                rs.getString("username"),
                rs.getInt("score"),
                rs.getString("grade")
            });
        }

        if (model.getRowCount() == 0) {
            model.addRow(new Object[]{"—", "Belum ada skor", "—", "—"});
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load leaderboard: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEasy;
    private javax.swing.JButton btnHard;
    private javax.swing.JButton btnNormal;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable leaderboardTable;
    private javax.swing.JList<String> songList;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
