/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rhythmain.ui;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

import rhythmain.dao.SongDAO;
import rhythmain.model.Song;
import rhythmain.ui.SongCardPanel;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.border.CompoundBorder;
import rhythmain.dao.ScoreDAO;
import rhythmain.ui.ScoreCardPanel;


/**
 *
 * @author LENOVO
 */
public class SongSelectionFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SongSelectionFrame.class.getName());

    /**
     * Creates new form SongSelectionFrame
     */
    public SongSelectionFrame() {
        initComponents();
        loadSongs();
        loadLeaderboard();
        
    }
    private Song selectedSong = null;
    private String selectedDifficulty = "Easy";
    
    private void loadSongs() {

        SongDAO dao =
                new SongDAO();

        List<Song> songs =
                dao.getAllSongs();
        
        if(!songs.isEmpty()) {

            showSongInfo(
                    songs.get(0)
            );

        }

        pnlSongContainer.removeAll();

        for (Song song : songs) {

            SongCardPanel card =
                    new SongCardPanel(song);

            card.addMouseListener(
                new java.awt.event.MouseAdapter() {

                    @Override
                    public void mouseClicked(
                            java.awt.event.MouseEvent evt) {

                        showSongInfo(song);
                        selectedSong = song;
                    }

                }
            );

            pnlSongContainer.add(card);
        }

        pnlSongContainer.revalidate();

        pnlSongContainer.repaint();
    }
    private void showSongInfo(
        Song song) {

        lblSongTitle.setText(
                song.getTitle()
        );

        lblSongArtist.setText(
                song.getArtist()
        );

        lblSongCreator.setText(
                song.getCreator()
        );

        SongDifficulty.setText(
                getDifficulty(
                        song.getBpm()
                )
        );

    }
    
    private String getDifficulty(
        double bpm) {

        if(bpm <= 130) {
            return "Easy";
        }

        if(bpm <= 140) {
            return "Normal";
        }

        return "Hard";
    }
    private void loadLeaderboard() {
        
        

        pnlLeaderboardContainer.removeAll();

        try {

            ScoreDAO dao =
                new ScoreDAO();

            ResultSet rs =
                dao.getTop10Scores();

            int rank = 1;

            while(rs.next()) {

                String username =
                    rs.getString("username");

                int score =
                    rs.getInt("best_score");
                
//                System.out.println( username + " " + score);

                ScoreCardPanel card =
                    new ScoreCardPanel(
                        rank,
                        username,
                        score
                    );
                card.setBorder(
                   BorderFactory.createEmptyBorder(
                            5,
                            5,
                            5,
                            5
                   )
                );
                
                card.setBorder(
                    BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(
                            new Color(
                                255,
                                255,
                                255,
                                30
                            ),
                            1
                        ),
                        BorderFactory.createEmptyBorder(
                            5,
                            5,
                            5,
                            5
                        )
                    )
                );

                pnlLeaderboardContainer.add(card);

                rank++;
            }

        } catch(Exception e) {

            e.printStackTrace();

        }

        pnlLeaderboardContainer.revalidate();

        pnlLeaderboardContainer.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        txtSearchSong = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        scrLeaderboard = new javax.swing.JScrollPane();
        pnlLeaderboardContainer = new javax.swing.JPanel();
        pnlSongInfo = new javax.swing.JPanel();
        lblSongCover = new javax.swing.JPanel();
        lblSongTitle = new javax.swing.JLabel();
        lblSongArtist = new javax.swing.JLabel();
        lblSongDuration = new javax.swing.JLabel();
        songDuration = new javax.swing.JLabel();
        lblSongDifficulty = new javax.swing.JLabel();
        SongDifficulty = new javax.swing.JLabel();
        lblSongCreator = new javax.swing.JLabel();
        SongCreator = new javax.swing.JLabel();
        scrSongList = new javax.swing.JScrollPane();
        pnlSongContainer = new javax.swing.JPanel();
        pnlDifficulty = new javax.swing.JPanel();
        btnEasy = new javax.swing.JButton();
        btnNormal = new javax.swing.JButton();
        btnHard = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        lblSongCover1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Song Selection");
        setFocusCycleRoot(false);
        setPreferredSize(new java.awt.Dimension(875, 600));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(15, 23, 42));
        mainPanel.setPreferredSize(new java.awt.Dimension(900, 700));

        pnlHeader.setBackground(new java.awt.Color(15, 23, 42));
        pnlHeader.setAlignmentX(0.0F);
        pnlHeader.setAlignmentY(0.0F);

        lblLogo.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblLogo.setForeground(java.awt.Color.cyan);
        lblLogo.setText("RhythMain");

        txtSearchSong.setText("Cari Lagu....");
        txtSearchSong.setPreferredSize(new java.awt.Dimension(250, 20));

        btnBack.setText("<-");
        btnBack.addActionListener(this::btnBackActionPerformed);

        lblUsername.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Player 3");

        lblLevel.setForeground(java.awt.Color.cyan);
        lblLevel.setText("Lv. 100");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblLogo)
                .addGap(68, 68, 68)
                .addComponent(txtSearchSong, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLevel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSearchSong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLevel))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblLogo)))
                .addGap(14, 14, 14))
        );

        pnlLeaderboardContainer.setBackground(new java.awt.Color(15, 23, 42));
        pnlLeaderboardContainer.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.cyan, 2));
        pnlLeaderboardContainer.setPreferredSize(new java.awt.Dimension(275, 480));
        pnlLeaderboardContainer.setLayout(new java.awt.GridLayout(0, 1, 0, 5));
        scrLeaderboard.setViewportView(pnlLeaderboardContainer);

        pnlSongInfo.setBackground(new java.awt.Color(15, 23, 47));
        pnlSongInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, null, null));
        pnlSongInfo.setPreferredSize(new java.awt.Dimension(130, 130));

        lblSongCover.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout lblSongCoverLayout = new javax.swing.GroupLayout(lblSongCover);
        lblSongCover.setLayout(lblSongCoverLayout);
        lblSongCoverLayout.setHorizontalGroup(
            lblSongCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        lblSongCoverLayout.setVerticalGroup(
            lblSongCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSongTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblSongTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSongTitle.setText("Twinkle Twinkle Little Star");

        lblSongArtist.setForeground(new java.awt.Color(255, 255, 255));
        lblSongArtist.setText("TwoTwo Ent.");

        lblSongDuration.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblSongDuration.setForeground(new java.awt.Color(255, 255, 255));
        lblSongDuration.setText("Duration");

        songDuration.setForeground(new java.awt.Color(255, 255, 255));
        songDuration.setText("03:00");

        lblSongDifficulty.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblSongDifficulty.setForeground(new java.awt.Color(255, 255, 255));
        lblSongDifficulty.setText("Difficulty");

        SongDifficulty.setForeground(new java.awt.Color(255, 255, 255));
        SongDifficulty.setText("Hard");

        lblSongCreator.setForeground(new java.awt.Color(255, 255, 255));
        lblSongCreator.setText("Tasya");

        SongCreator.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        SongCreator.setForeground(new java.awt.Color(255, 255, 255));
        SongCreator.setText("Creator");

        javax.swing.GroupLayout pnlSongInfoLayout = new javax.swing.GroupLayout(pnlSongInfo);
        pnlSongInfo.setLayout(pnlSongInfoLayout);
        pnlSongInfoLayout.setHorizontalGroup(
            pnlSongInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSongInfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblSongCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSongInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSongInfoLayout.createSequentialGroup()
                        .addGroup(pnlSongInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSongTitle)
                            .addComponent(lblSongArtist))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlSongInfoLayout.createSequentialGroup()
                        .addGroup(pnlSongInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSongDuration)
                            .addComponent(songDuration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(pnlSongInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSongDifficulty)
                            .addComponent(SongDifficulty))
                        .addGap(73, 73, 73)
                        .addGroup(pnlSongInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSongCreator)
                            .addComponent(SongCreator))
                        .addGap(61, 61, 61))))
        );
        pnlSongInfoLayout.setVerticalGroup(
            pnlSongInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSongInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblSongTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSongArtist)
                .addGap(18, 18, 18)
                .addGroup(pnlSongInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSongInfoLayout.createSequentialGroup()
                        .addComponent(lblSongDuration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(songDuration))
                    .addGroup(pnlSongInfoLayout.createSequentialGroup()
                        .addComponent(lblSongDifficulty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SongDifficulty))
                    .addGroup(pnlSongInfoLayout.createSequentialGroup()
                        .addComponent(SongCreator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSongCreator)))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(pnlSongInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSongCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSongContainer.setBackground(new java.awt.Color(15, 23, 47));
        pnlSongContainer.setLayout(new java.awt.GridLayout(0, 1, 0, 5));
        scrSongList.setViewportView(pnlSongContainer);
        pnlSongContainer.getAccessibleContext().setAccessibleName("");

        pnlDifficulty.setBackground(new java.awt.Color(15, 23, 42));

        btnEasy.setBackground(new java.awt.Color(0, 204, 51));
        btnEasy.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEasy.setText("EASY");
        btnEasy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEasyMouseClicked(evt);
            }
        });

        btnNormal.setBackground(new java.awt.Color(255, 255, 0));
        btnNormal.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnNormal.setText("NORMAL");
        btnNormal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNormalMouseClicked(evt);
            }
        });

        btnHard.setBackground(new java.awt.Color(255, 51, 51));
        btnHard.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnHard.setText("HARD");
        btnHard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHardMouseClicked(evt);
            }
        });

        btnPlay.setBackground(new java.awt.Color(0, 204, 204));
        btnPlay.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(204, 255, 255));
        btnPlay.setText("PLAY");
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        btnPlay.addActionListener(this::btnPlayActionPerformed);

        javax.swing.GroupLayout pnlDifficultyLayout = new javax.swing.GroupLayout(pnlDifficulty);
        pnlDifficulty.setLayout(pnlDifficultyLayout);
        pnlDifficultyLayout.setHorizontalGroup(
            pnlDifficultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDifficultyLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnEasy, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHard, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDifficultyLayout.setVerticalGroup(
            pnlDifficultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDifficultyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlDifficultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEasy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHard, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDifficultyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblSongCover1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOP 10 SCORES");

        javax.swing.GroupLayout lblSongCover1Layout = new javax.swing.GroupLayout(lblSongCover1);
        lblSongCover1.setLayout(lblSongCover1Layout);
        lblSongCover1Layout.setHorizontalGroup(
            lblSongCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblSongCover1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblSongCover1Layout.setVerticalGroup(
            lblSongCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblSongCover1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrLeaderboard, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(lblSongCover1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scrSongList, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlSongInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
                    .addComponent(pnlDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(pnlSongInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrSongList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(lblSongCover1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnEasyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEasyMouseClicked
        // TODO add your handling code here:

        selectedDifficulty = "Easy";

        btnEasy.setBackground(Color.GREEN);

        btnNormal.setBackground(
                new Color(60,60,60));

        btnHard.setBackground(
                new Color(60,60,60));

    }//GEN-LAST:event_btnEasyMouseClicked

    private void btnNormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNormalMouseClicked
        // TODO add your handling code here:
        selectedDifficulty = "Normal";

        btnNormal.setBackground(Color.YELLOW);

        btnEasy.setBackground(
                new Color(60,60,60));

        btnHard.setBackground(
                new Color(60,60,60));
    }//GEN-LAST:event_btnNormalMouseClicked

    private void btnHardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHardMouseClicked
        // TODO add your handling code here:
         selectedDifficulty = "Hard";

        btnHard.setBackground(Color.RED);

        btnEasy.setBackground(
                new Color(60,60,60));

        btnNormal.setBackground(
                new Color(60,60,60));
    }//GEN-LAST:event_btnHardMouseClicked

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        // TODO add your handling code here:
        
        if(selectedSong == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Pilih lagu terlebih dahulu!"
            );

            return;
            }

            JOptionPane.showMessageDialog(
                    this,

                    "Lagu : "
                    + selectedSong.getTitle()

                    + "\nDifficulty : "

                    + selectedDifficulty
            );
            
            GameplayFrame frame = new GameplayFrame(selectedSong, selectedDifficulty);
            frame.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnPlayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SongSelectionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SongCreator;
    private javax.swing.JLabel SongDifficulty;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEasy;
    private javax.swing.JButton btnHard;
    private javax.swing.JButton btnNormal;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSongArtist;
    private javax.swing.JPanel lblSongCover;
    private javax.swing.JPanel lblSongCover1;
    private javax.swing.JLabel lblSongCreator;
    private javax.swing.JLabel lblSongDifficulty;
    private javax.swing.JLabel lblSongDuration;
    private javax.swing.JLabel lblSongTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlDifficulty;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLeaderboardContainer;
    private javax.swing.JPanel pnlSongContainer;
    private javax.swing.JPanel pnlSongInfo;
    private javax.swing.JScrollPane scrLeaderboard;
    private javax.swing.JScrollPane scrSongList;
    private javax.swing.JLabel songDuration;
    private javax.swing.JTextField txtSearchSong;
    // End of variables declaration//GEN-END:variables

    private void setBorder(CompoundBorder createCompoundBorder) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
